apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: web
spec:
  containers:
  - name: redis
    image: redis:6.2
    ports:
    - containerPort: 6379
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80