apiVersion: v1
kind: Pod
metadata:
  name: memcached-pod
  labels:
    app: web
spec:
  containers:
  - name: memcached
    image: memcached
    ports:
    - containerPort: 11211
    resources:
      requests:
        cpu: 0.35
        memory: 150Mi
      limits:
        cpu: 0.5
        memory: 250Mi
  restartPolicy: Never
